$('.owl-carousel').owlCarousel({
    loop:false,
    margin:28,
    nav:true,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:3
        },
        1000:{
            items:6
        }
    }
})